apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: nats
spec:
  interval: 1m
  chart:
    spec:
      chart: "nats"
      version: ">=0.13"
      sourceRef:
        kind: HelmRepository
        name: nats
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: configmap-nats
      valuesKey: nats-values.yaml
